-- This is the role that should be granted to the DB user used by the application:
CREATE ROLE app;
ALTER ROLE app NOBYPASSRLS;

-- This table stores all possible tenants.
-- Other tables storing tenant-specific data must have a foreign key to here:
CREATE TABLE tenants (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tenants TO app;

-- Enable RLS on the tenants table, and FORCE the table owner to be subject to RLS as well.
-- (however the owner is superuser here so they can bypass RLS nevertheless)
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;

-- Define the policy that applies to the application users.
-- USING applies to existing rows (reading), while WITH CHECK applies to new rows (writing).
-- Here, WITH CHECK is implicitly the same as USING.
CREATE POLICY tenants_rls_app ON tenants AS RESTRICTIVE TO app USING (
	id = ANY(current_setting('app.tenant')::BIGINT[])
);
-- Policies can be either permissive (default) or restrictive.
-- Access to a row is granted if ANY of the permissive policies pass AND ALL of the restrictive policies pass.
-- If data isolation is only ensured with permissive policies, one could always add another permissive policy to grant access to all rows:
--
-- 			CREATE POLICY tenants_rls_app_malicious ON tenants TO app USING (true);
--
-- To avoid this, the 'tenants_rls_app' is restrictive and thus must always pass.
-- However, if no permissive policies are present, no access is granted to any rows.
-- Thus, we still do need to add a permissive policy (now not malicious):
CREATE POLICY tenants_rls_perm_app ON tenants TO app USING (true);

-- The documents table is similarly defined.
-- Each row references a tenant (or is null).
-- We can define the policy such that only rows with the current tenant or without one are accessible.
CREATE TABLE documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	contents TEXT NOT NULL,
	tenant BIGINT REFERENCES tenants(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON documents TO app;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
CREATE POLICY documents_rls_app ON documents AS RESTRICTIVE TO app USING (
	tenant IS NULL OR tenant = ANY(current_setting('app.tenant')::BIGINT[])
);
CREATE POLICY documents_rls_perm_app ON documents TO app USING (true);



-- It is possible to 'delegate' tenancy information to a referenced entity (from notes to documents).
-- The subselect on 'documents' will apply that table's policy (no need to add
-- a condition on 'documents.tenant' again).
CREATE TABLE notes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	contents TEXT NOT NULL,
	document BIGINT NOT NULL REFERENCES documents(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO app;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes FORCE ROW LEVEL SECURITY;
CREATE POLICY notes_rls_app ON notes AS RESTRICTIVE TO app USING (
	notes.document IN (SELECT documents.id FROM documents)
);
CREATE POLICY notes_rls_perm_app ON notes TO app USING (true);
-- However, for performance reasons, it might be best to avoid subqueries and store tenant
-- in this table in a column instead.



-- The tags demonstrate a many-to-many relationship.
CREATE TABLE tags (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	tenant BIGINT REFERENCES tenants(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tags TO app;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags FORCE ROW LEVEL SECURITY;
CREATE POLICY tags_rls_app ON tags AS RESTRICTIVE TO app USING (
	tenant is NULL OR tenant = ANY(current_setting('app.tenant')::BIGINT[])
);
CREATE POLICY tags_rls_perm_app ON tags TO app USING (true);
-- We can omit 'tenant' from the junction table, as joining to either 'tags' or 'documents'
-- will filter out rows that belong to other tenants.
-- Thus we can only do checks on writing:
CREATE TABLE tags_to_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag BIGINT REFERENCES tags(id),
	document BIGINT REFERENCES documents(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tags_to_documents TO app;
ALTER TABLE tags_to_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags_to_documents FORCE ROW LEVEL SECURITY;
-- Adding a 'tenant' column and setting up "USING (tenant IS NULL OR tenant = ANY(current_setting(\'app.tenant')::BIGINT[]))"
-- will not be enough here, as a connection for one tenant could create entries linking tags and documents of another tenant.
-- The following will join the tables to verify:
--
-- 			CREATE POLICY tags_2_documents_rls_app ON tags_2_documents TO app USING (true) WITH CHECK (
-- 				EXISTS (SELECT 1 FROM tags WHERE tags.id = tags_2_documents.tag)
-- 					AND
-- 				EXISTS (SELECT 1 FROM documents WHERE documents.id = tags_2_documents.document)
-- 			);
--
-- However, even though we can't expose other tenants' tags or documents, we can expose how many of each they have, and their IDs.
-- Thus it might be better to enable read checks as well.
-- Moreover, joins can be avoided, which can increase performance:
CREATE POLICY tags_to_documents_rls_app ON tags_to_documents AS RESTRICTIVE TO app USING (
	tags_to_documents.tag IN (SELECT tags.id FROM tags)
		AND
	tags_to_documents.document IN (SELECT documents.id FROM documents)
);
CREATE POLICY tags_to_documents_rls_perm_app ON tags_to_documents TO app USING (true);



-- Views are executed with the priveleges of the owner, regardless of the priveleges of the user
-- accessing the view.
-- Thus, if the superuser or a user with BYPASSRLS enabled is the owner, any user accessing the view will also bypass RLS.
-- To avoid this, the 'security_invoker' flag is required, which will use the current user's permissions:
CREATE VIEW documents_with_tags
WITH (security_invoker)
AS SELECT
	d.id,
	d.name,
	d.contents,
	string_agg(t.name, ', ') AS tags,
	(SELECT count(1) FROM notes WHERE notes.document = d.id) AS notes_amount,
	(SELECT count(1) FROM notes) AS notes_total,
	d.tenant
FROM documents d
	JOIN tags_2_documents t2d ON d.id = t2d.document
	JOIN tags t ON t2d.tag = t.id
GROUP BY d.id;
GRANT SELECT ON documents_with_tags TO app;
-- It is possible to audit views for this flag (see scripts/security-invoker.sql).



-- If we want to assign users to many tenants, we can use a junction table and omit tenancy
-- information from the 'users' table:
CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	name TEXT NOT NULL,
	last_login TIMESTAMP WITH TIME ZONE
);
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO app;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
-- Which will require a bit more complicated policy however:
CREATE POLICY users_rls_app ON users AS RESTRICTIVE TO app USING (
	EXISTS (
		SELECT 1 FROM users_to_tenants utt
		WHERE utt."user" = users.id AND utt.tenant = ANY(current_setting('app.tenant')::BIGINT[])
	)
);
CREATE POLICY users_rls_perm_app ON users TO app USING (true);
-- The junction table's policy is a lot simpler:
CREATE TABLE users_to_tenants (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user" BIGINT NOT NULL REFERENCES users(id),
	tenant BIGINT NOT NULL REFERENCES tenants(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON users_to_tenants TO app;
ALTER TABLE users_to_tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_to_tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY users_to_tenants_rls_app ON users_to_tenants AS RESTRICTIVE TO app USING (
	users_to_tenants.tenant = ANY(current_setting('app.tenant')::BIGINT[])
);
CREATE POLICY users_to_tenants_rls_perm_app ON users_to_tenants TO app USING (true);

-- For authentication, this setup provides a challenge if using a user with the 'app' role,
-- as it cannot bypass RLS, rendering looking up users before authentication impossible.
-- For this reason, we can introduce a restrictive 'auth' role, which can only read the user tables:
CREATE ROLE auth;
-- For some reason, setting BYPASSRLS on the role does not stop RLS checks.
-- 			ALTER ROLE auth BYPASSRLS;
-- For the auth user to be able to see any entries, the following is required:
-- 			ALTER USER <auth_username> BYPASSRLS;
GRANT SELECT ON users TO auth;
GRANT SELECT ON users_to_tenants TO auth;
GRANT SELECT ON tenants TO auth;
