-- This is the role that should be granted to the DB user used by the application:
CREATE ROLE app;
ALTER ROLE app NOBYPASSRLS;

-- This table stores all possible tenants.
-- Other tables storing tenant-specific data must have a foreign key to here:
CREATE TABLE tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tenants TO app;

-- Enable RLS on the tenants table, and FORCE the table owner to be subject to RLS as well.
-- (however the owner is superuser here so they can bypass RLS nevertheless)
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;

-- Define the policy that applies to the application users.
-- USING applies to existing rows (reading), while WITH CHECK applies to new rows (writing).
-- Here, WITH CHECK is implicitly the same as USING.
CREATE POLICY tenants_rls_app ON tenants TO app USING (
	id = current_setting('app.tenant')::BIGINT
);



-- The documents table is similarly defined. Each row references a tenant (or is null).
-- We can define the policy such that only rows with the current tenant or without one are accessible.
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contents TEXT NOT NULL,
    tenant BIGINT REFERENCES tenants(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON documents TO app;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
CREATE POLICY documents_rls_app ON documents TO app USING (
	tenant IS NULL OR tenant = current_setting('app.tenant')::BIGINT
);



-- It is possible to 'delegate' tenancy information to a referenced entity (from notes to documents).
-- The subselect on 'documents' will apply that table's policy (no need to add
-- a condition on 'documents.tenant' again).
CREATE TABLE notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contents TEXT NOT NULL,
	document BIGINT NOT NULL REFERENCES documents(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO app;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes FORCE ROW LEVEL SECURITY;
CREATE POLICY notes_rls_app ON notes TO app USING (
	EXISTS (SELECT 1 FROM documents WHERE documents.id = notes.document)
);
-- However, for performance reasons, it might be best to avoid subqueries and store tenant
-- in this table in a column instead.



-- The tags demonstrate a many-to-many relationship.
CREATE TABLE tags (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	tenant BIGINT REFERENCES tenants(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tags TO app;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags FORCE ROW LEVEL SECURITY;
CREATE POLICY tags_rls_app ON tags TO app USING (
	tenant is NULL OR tenant = current_setting('app.tenant')::BIGINT
);
-- We can omit 'tenant' from the junction table, as joining to either 'tags' or 'documents'
-- will filter out rows that belong to other tenants. Thus we can only do checks on writing:
CREATE TABLE tags_2_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag BIGINT REFERENCES tags(id),
	document BIGINT REFERENCES documents(id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON tags_2_documents TO app;
ALTER TABLE tags_2_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags_2_documents FORCE ROW LEVEL SECURITY;
-- Adding a 'tenant' column and setting up "USING (tenant IS NULL OR tenant = current_setting(\'app.tenant')::BIGINT)"
-- will not be enough here, as a connection for one tenant could create entries for another.
-- The following will join the tables to verify:
--
-- 			CREATE POLICY tags_2_documents_rls_app ON tags_2_documents TO app USING (true) WITH CHECK (
-- 				EXISTS (SELECT 1 FROM tags WHERE tags.id = tags_2_documents.tag)
-- 					AND
-- 				EXISTS (SELECT 1 FROM documents WHERE documents.id = tags_2_documents.document)
-- 			);
--
-- However, even though we can't expose other tenants' tags or documents, we can expose how many of each they have,
-- and their IDs. Thus it might be better to enable read checks as well. Moreover, joins can be
-- avoided, which can increase performance:
CREATE POLICY tags_2_documents_rls_app ON tags_2_documents TO app USING (
	tags_2_documents.tag IN (SELECT tags.id FROM tags)
		AND
	tags_2_documents.document IN (SELECT documents.id FROM documents)
);

-- TODO: restrictive/permissive policies
