spring:
  application:
    name: sb-multitenant-demo

server:
  port: ${SB_PORT:8080}

datasource:
  app:
    jdbc-url: ${DB_URL}
    username: ${APP_POSTGRES_USERNAME}
    password: ${APP_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  auth:
    jdbc-url: ${DB_URL}
    username: ${APP_AUTH_POSTGRES_USERNAME}
    password: ${APP_AUTH_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate:
      # log SQL statements (DEBUG):
      SQL: INFO
      # log bound parameters (TRACE):
      orm.jdbc.bind: INFO
